import requests
from django.conf import settings
class OllamaClient:
    def __init__(self):
        self.host = getattr(settings, "LLM_HOST", "http://localhost:11434")
        self.chat_model = getattr(settings, "LLM_MODEL", "qwen2.5:1.5b")
        self.embed_model = getattr(settings, "EMBED_MODEL", "nomic-embed-text")
    def chat(self, messages: list[dict], tools: list = None) -> dict:
        """Chat with Ollama.
        If tools provided, returns full JSON response containing tool_calls.
        If no tools, returns dict with message.content.
        Typical return shapes:
        - No tool: {"message": {"role": "assistant", "content": "..."}}
        - Tool called: {"message": {"role": "assistant", "tool_calls": [...]}}
        """ """Code generated by Opus4.6 ,do not edit this ,only for understanding"""
        payload = {
            "model": self.chat_model,
            "messages": messages,
            "stream": False,
        }
        if tools:
            payload["tools"] = tools

        try:
            r = requests.post(
                f"{self.host}/api/chat",
                json=payload,
                timeout=60,
            )
            r.raise_for_status()
        except requests.exceptions.ConnectionError:
            raise RuntimeError(
                f"Cannot reach Ollama at {self.host}. "
                "Make sure Ollama is running: `ollama serve`"
            )
        except requests.exceptions.Timeout:
            raise RuntimeError(
                f"Ollama chat request timed out after 60s "
                f"(model: {self.chat_model}). The model may still be loading."
            )
        except requests.exceptions.HTTPError as e:
            raise RuntimeError(f"Ollama returned an error: {e.response.status_code} {e.response.text}")
        return r.json()
    def embed(self, text: str) -> list[float]:
        try:
            r = requests.post(
                f"{self.host}/api/embeddings",
                json={"model": self.embed_model, "prompt": text},
                timeout=30,
            )
            r.raise_for_status()
        except requests.exceptions.ConnectionError:
            raise RuntimeError(
                f"Cannot reach Ollama at {self.host}. "
                "Make sure Ollama is running: `ollama serve`"
            )
        except requests.exceptions.Timeout:
            raise RuntimeError(
                f"Ollama embed request timed out after 30s "
                f"(model: {self.embed_model}). The model may still be loading."
            )
        except requests.exceptions.HTTPError as e:
            raise RuntimeError(f"Ollama returned an error: {e.response.status_code} {e.response.text}")
        return r.json()["embedding"]